version: '3'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: my.env
    environment:
      TZ: "Asia/Tokyo"

    ports:
      - 3306:3306
    volumes:
      - mysql4cbc6web:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d/

  apache_php_py:
    build:
      context: .
      dockerfile: ./apache_php_py/Dockerfile

    ports:
      - 80:80
    volumes:
      - ./localhost/htdocs:/var/www/localhost/htdocs
      - ./localhost/cgi-bin:/var/www/localhost/cgi-bin

#    restart: always
    depends_on:
      - mysql

volumes:
  mysql4cbc6web: